### ISSUE TITLE
No fasta file when running the pipeline in local computer

### ISSUE THREAD

**Issue by efratushava** [nf-core/methylseq#122]
Hello,

I'm trying to run the pipeline after cloning to my local computer:
```
nextflow -log methylseq_log run methylseq/main.nf --aligner 'bwameth' --reads 'data/run_bwameth/fastq_files/*/*sorted_{1,2}.fastq' -profile singularity --genome 'GRCh37' --outdir 'data/run_bwameth/nextflow' --email blabla@gmail.com --email_on_fail blabla@gmail.com --name try_pipeline
```

and I get the error `No Fasta reference specified!`
The fasta parameter is actually false, but why? printing `${params.genomes[params.genome].fasta}` gives me the right fasta file `s3://ngi-igenomes/igenomes//Homo_sapiens/Ensembl/GRCh37/Sequence/WholeGenomeFasta/genome.fa.`
So why does the fasta parameter get false value?

The config file, after all defaults jas this lines:
```
Nov-25 13:07:50.844 [main] DEBUG nextflow.Session - Session aborted -- Cause: No Fasta reference specified! false, s3://ngi-igenomes/igenomes//Homo_sapiens/Ensembl/GRCh37/Sequence/WholeGenomeFasta/genome.fa. Expression: params.fasta
Nov-25 13:07:50.866 [main] ERROR nextflow.cli.Launcher - @unknown
java.lang.AssertionError: No Fasta reference specified!  Expression: params.fasta
        at org.codehaus.groovy.runtime.InvokerHelper.assertFailed(InvokerHelper.java:417)
        at org.codehaus.groovy.runtime.ScriptBytecodeAdapter.assertFailed(ScriptBytecodeAdapter.java:670)
        at Script_372c9fdc.runScript(Script_372c9fdc:134)
        at nextflow.script.BaseScript.run0(BaseScript.groovy:152)
        at nextflow.script.BaseScript.run(BaseScript.groovy:182)
        at nextflow.script.ScriptParser.runScript(ScriptParser.groovy:217)
        at nextflow.script.ScriptRunner.run(ScriptRunner.groovy:218)
        at nextflow.script.ScriptRunner.execute(ScriptRunner.groovy:126)
        at nextflow.cli.CmdRun.run(CmdRun.groovy:257)
        at nextflow.cli.Launcher.run(Launcher.groovy:457)
        at nextflow.cli.Launcher.main(Launcher.groovy:639)

```

**Comment by ewels** [comment]
Same issue as in #121, closing to continue discussion there.
