### ISSUE TITLE
Error when modifying base.config

### ISSUE THREAD

**Issue by pterzian** [nf-core/methylseq#158]
Hi,

I had some memory issue with `qualimap` and `preseq` for the R2 reads of one library. 
Because I am pretty sure it was a lack of memory issue (specifically happening with samtools sort) I wanted to modify the base.config memory parameter for the `qualimap` process. So I saved the new config in a new file and gave it to the `-c` parameter in my nextflow command. Then I get this :  
```nextflow
Exception in thread "Task submitter" groovy.lang.MissingMethodException: No signature of method: _nf_script_0cfebac4.check_max() is applicable for argument types: (Integer, String) values: [1, c
pus]
        at org.codehaus.groovy.runtime.ScriptBytecodeAdapter.unwrap(ScriptBytecodeAdapter.java:70)
        at groovy.lang.GroovyObject$invokeMethod$1.call(Unknown Source)
        at nextflow.processor.TaskContext.invokeMethod(TaskContext.groovy:147)
        at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeOnDelegationObjects(ClosureMetaClass.java:397)
        at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:339)
        at org.codehaus.groovy.runtime.callsite.PogoMetaClassSite.callCurrent(PogoMetaClassSite.java:64)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:176)
        at _nf_config_e4baa6f5$_run_closure1$_closure3.doCall(_nf_config_e4baa6f5:15)
        at _nf_config_e4baa6f5$_run_closure1$_closure3.doCall(_nf_config_e4baa6f5)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:497)
        at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:101)
        at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:323)
        at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:263)
        at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1041)
        at groovy.lang.Closure.call(Closure.java:405)
        at groovy.lang.Closure.call(Closure.java:399)
        at nextflow.processor.LazyMap.resolveImpl(TaskConfig.groovy:493)
        at nextflow.processor.LazyMap.resolveImpl(TaskConfig.groovy)
        at nextflow.processor.LazyMap.resolve(TaskConfig.groovy:454)
        at nextflow.processor.LazyMap.get(TaskConfig.groovy:517)
        at nextflow.processor.TaskConfig.get(TaskConfig.groovy:108)
        at nextflow.processor.TaskConfig.getCpus(TaskConfig.groovy:242)
        at nextflow.processor.TaskConfig$getCpus$4.call(Unknown Source)
        at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:47)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:115)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:119)
        at nextflow.processor.TaskHandler.getTraceRecord(TaskHandler.groovy:171)
        at nextflow.executor.GridTaskHandler.super$2$getTraceRecord(GridTaskHandler.groovy)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:497)
        at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:101)
        at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:323)
        at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1217)
        at org.codehaus.groovy.runtime.ScriptBytecodeAdapter.invokeMethodOnSuperN(ScriptBytecodeAdapter.java:144)
        at org.codehaus.groovy.runtime.ScriptBytecodeAdapter.invokeMethodOnSuper0(ScriptBytecodeAdapter.java:164)
        at nextflow.executor.GridTaskHandler.getTraceRecord(GridTaskHandler.groovy:389)
        at nextflow.Session.notifyTaskComplete(Session.groovy:923)
        at nextflow.processor.TaskPollingMonitor.submitPendingTasks(TaskPollingMonitor.groovy:575)
        at nextflow.processor.TaskPollingMonitor.submitLoop(TaskPollingMonitor.groovy:396)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:497)
        at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:101)
        at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:323)
        at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1217)
        at groovy.lang.MetaClassImpl.invokeMethodClosure(MetaClassImpl.java:1050)
        at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1092)
        at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1041)
        at groovy.lang.Closure.call(Closure.java:405)
        at groovy.lang.Closure.call(Closure.java:399)
        at groovy.lang.Closure.run(Closure.java:486)
        at java.lang.Thread.run(Thread.java:745)
ERROR ~ Error executing process > 'fastqc (152-2_CACGAT-AHGCLWBBXY_L006)'

Caused by:
  No signature of method: check_max() is applicable for argument types: (Integer, String) values: [1, cpus]

Source block:
  """
  fastqc --quiet --threads $task.cpus $reads
  """

Tip: you can replicate the issue by changing to the process work dir and entering the command `bash .command.run`

 -- Check '.nextflow.log' file for details
Execution cancelled -- Finishing pending tasks before exit
```
Am I doing wrong when giving the new config directly to the `-c` parameter of nextflow (it worked great before) ? Also it is maybe worth mentionning I am calling the genotoul profile in my command.

Thank you for providing this pipeline !

Paul

**Comment by ewels** [comment]
Hi @pterzian,

Config instructions here: https://nf-co.re/usage/configuration - but I think you're doing everything right.

I guess that this is because you copied and pasted the `check_max()` function from `base.config` in to your new custom configuration file. This won't work outside of the main pipeline config files unfortunately.

Could you try removing that function call from your config and see if that works? If it doesn't, could you please post the contents of the custom config file that you are using please?

Thanks,

Phil

**Comment by pterzian** [comment]
Hi Phil,

Thank you for your answer. Actually I simply edited a copy of `nf-core/methylseq/conf/base.config` and changed its name. I then edited only two caracters :
```
memory = { check_max( 32.GB * task.attempt, 'memory') }
```
into 
```
memory = { check_max (64.GB * task.attempt, 'memory') }
```

Are you saying I should remove the `check_max()` everywhere I find it ? and go something like :
```
 withName:qualimap {
    cpus = { 4 * task.attempt }
    memory = { 64.GB * task.attempt }
  }
and so on..
```

**Comment by ewels** [comment]
Yes exactly. And it’s not a good idea to copy the whole config - only keep the bits you need to overwrite if you can.

**Comment by pterzian** [comment]
Ha ! I didn't get I could overwrite one process only with the custom config.
Thanks a bunch!

**Comment by ewels** [comment]
No problem!
